language: rust

os:
  - linux
  - osx
rust: stable
sudo: false
cache:
  bundler: true
  cargo: true
  directories:
    - /home/travis/.cargo
    - $TRAVIS_BUILD_DIR/vendor/bundle

rvm:
  - 2.7.0
before_install: gem install bundler -v 2.1.2

script: |
  bundle install
  bundle exec rake
